language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install
- npm install -g bower grunt-cli
- gem install sass
- bower install
- grunt
services: mongodb
before_deploy: "rm .gitignore"
deploy:
  provider: heroku
  username: alfonso.presa@gmail.com
  app: stocks-alfonso-presa
  skip_cleanup: true
  api_key:
    secure: "ofBcjUplzZlShnVTn5qxQAoghuBISFV+xXiPd9/5wIuWodLT1Lor43p6fiLTF1z95kQpVPg3m7czRGOCZtuU3yajWtFeMiqaLiyLBPQcXo42iqJiKFtV02GbpVm8q5FAKQiOYRJhNY8Z+GMurAR/nSVtcnhkP0GokCPdIkiBZg8="
